# Generated by Django 5.1.3 on 2024-11-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
