# Generated by Django 5.1.3 on 2024-11-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteInfo', '0003_alter_note_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Blog',
        ),
    ]
